#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

 #include "deepcnvwrap.h" 

/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 87), // void()(int, int, _Bool, _Bool, double * *, double * *, int, int, double, double, double, double, double, double, double, double, double, double, double, double, double, double, double * *, double * *, double *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double *, _Bool, _Bool, double *, double *, int *, int *, int *, int *, double *, double * *, int, double *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, double * *, int, int, double, double, double, double, double, double, double, double, _Bool, _Bool, _Bool, _Bool, double, double *, double *, double * *, double * *, double, double, double, double *, _Bool)
/*  1 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  2 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  3 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/*  4 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 25), // double * *
/*  6 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/*  7 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  8 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/*  9 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 10 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 11 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 12 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 13 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 14 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 15 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 16 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 17 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 18 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 19 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 20 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 21 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 22 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 25 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // double *
/* 26 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 35 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 37 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 38 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 39 */ _CFFI_OP(_CFFI_OP_POINTER, 1), // int *
/* 40 */ _CFFI_OP(_CFFI_OP_NOOP, 39),
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 39),
/* 42 */ _CFFI_OP(_CFFI_OP_NOOP, 39),
/* 43 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 44 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 45 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 46 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 47 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 48 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 49 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 50 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 51 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 52 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 53 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 54 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 55 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 56 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 57 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 58 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 59 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 60 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 61 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 62 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 63 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 64 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 65 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 66 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 67 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 68 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 69 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 70 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 71 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 72 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 73 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 74 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 75 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 76 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 77 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 78 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 79 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 80 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 81 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 82 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 83 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14),
/* 84 */ _CFFI_OP(_CFFI_OP_NOOP, 25),
/* 85 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1),
/* 86 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 87 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static void _cffi_d_samfdeepcnv_loop(int x0, int x1, _Bool x2, _Bool x3, double * * x4, double * * x5, int x6, int x7, double x8, double x9, double x10, double x11, double x12, double x13, double x14, double x15, double x16, double x17, double x18, double x19, double x20, double x21, double * * x22, double * * x23, double * x24, double * * x25, double * * x26, double * * x27, double * * x28, double * * x29, double * * x30, double * * x31, double * * x32, double * x33, _Bool x34, _Bool x35, double * x36, double * x37, int * x38, int * x39, int * x40, int * x41, double * x42, double * * x43, int x44, double * x45, double * * x46, double * * x47, double * * x48, double * * x49, double * * x50, double * * x51, double * * x52, double * * x53, double * * x54, double * * x55, double * * x56, double * * x57, double * * x58, double * * x59, double * * x60, int x61, int x62, double x63, double x64, double x65, double x66, double x67, double x68, double x69, double x70, _Bool x71, _Bool x72, _Bool x73, _Bool x74, double x75, double * x76, double * x77, double * * x78, double * * x79, double x80, double x81, double x82, double * x83, _Bool x84)
{
  samfdeepcnv_loop(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x50, x51, x52, x53, x54, x55, x56, x57, x58, x59, x60, x61, x62, x63, x64, x65, x66, x67, x68, x69, x70, x71, x72, x73, x74, x75, x76, x77, x78, x79, x80, x81, x82, x83, x84);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_samfdeepcnv_loop(PyObject *self, PyObject *args)
{
  int x0;
  int x1;
  _Bool x2;
  _Bool x3;
  double * * x4;
  double * * x5;
  int x6;
  int x7;
  double x8;
  double x9;
  double x10;
  double x11;
  double x12;
  double x13;
  double x14;
  double x15;
  double x16;
  double x17;
  double x18;
  double x19;
  double x20;
  double x21;
  double * * x22;
  double * * x23;
  double * x24;
  double * * x25;
  double * * x26;
  double * * x27;
  double * * x28;
  double * * x29;
  double * * x30;
  double * * x31;
  double * * x32;
  double * x33;
  _Bool x34;
  _Bool x35;
  double * x36;
  double * x37;
  int * x38;
  int * x39;
  int * x40;
  int * x41;
  double * x42;
  double * * x43;
  int x44;
  double * x45;
  double * * x46;
  double * * x47;
  double * * x48;
  double * * x49;
  double * * x50;
  double * * x51;
  double * * x52;
  double * * x53;
  double * * x54;
  double * * x55;
  double * * x56;
  double * * x57;
  double * * x58;
  double * * x59;
  double * * x60;
  int x61;
  int x62;
  double x63;
  double x64;
  double x65;
  double x66;
  double x67;
  double x68;
  double x69;
  double x70;
  _Bool x71;
  _Bool x72;
  _Bool x73;
  _Bool x74;
  double x75;
  double * x76;
  double * x77;
  double * * x78;
  double * * x79;
  double x80;
  double x81;
  double x82;
  double * x83;
  _Bool x84;
  Py_ssize_t datasize;
  struct _cffi_freeme_s *large_args_free = NULL;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;
  PyObject *arg4;
  PyObject *arg5;
  PyObject *arg6;
  PyObject *arg7;
  PyObject *arg8;
  PyObject *arg9;
  PyObject *arg10;
  PyObject *arg11;
  PyObject *arg12;
  PyObject *arg13;
  PyObject *arg14;
  PyObject *arg15;
  PyObject *arg16;
  PyObject *arg17;
  PyObject *arg18;
  PyObject *arg19;
  PyObject *arg20;
  PyObject *arg21;
  PyObject *arg22;
  PyObject *arg23;
  PyObject *arg24;
  PyObject *arg25;
  PyObject *arg26;
  PyObject *arg27;
  PyObject *arg28;
  PyObject *arg29;
  PyObject *arg30;
  PyObject *arg31;
  PyObject *arg32;
  PyObject *arg33;
  PyObject *arg34;
  PyObject *arg35;
  PyObject *arg36;
  PyObject *arg37;
  PyObject *arg38;
  PyObject *arg39;
  PyObject *arg40;
  PyObject *arg41;
  PyObject *arg42;
  PyObject *arg43;
  PyObject *arg44;
  PyObject *arg45;
  PyObject *arg46;
  PyObject *arg47;
  PyObject *arg48;
  PyObject *arg49;
  PyObject *arg50;
  PyObject *arg51;
  PyObject *arg52;
  PyObject *arg53;
  PyObject *arg54;
  PyObject *arg55;
  PyObject *arg56;
  PyObject *arg57;
  PyObject *arg58;
  PyObject *arg59;
  PyObject *arg60;
  PyObject *arg61;
  PyObject *arg62;
  PyObject *arg63;
  PyObject *arg64;
  PyObject *arg65;
  PyObject *arg66;
  PyObject *arg67;
  PyObject *arg68;
  PyObject *arg69;
  PyObject *arg70;
  PyObject *arg71;
  PyObject *arg72;
  PyObject *arg73;
  PyObject *arg74;
  PyObject *arg75;
  PyObject *arg76;
  PyObject *arg77;
  PyObject *arg78;
  PyObject *arg79;
  PyObject *arg80;
  PyObject *arg81;
  PyObject *arg82;
  PyObject *arg83;
  PyObject *arg84;

  if (!PyArg_UnpackTuple(args, "samfdeepcnv_loop", 85, 85, &arg0, &arg1, &arg2, &arg3, &arg4, &arg5, &arg6, &arg7, &arg8, &arg9, &arg10, &arg11, &arg12, &arg13, &arg14, &arg15, &arg16, &arg17, &arg18, &arg19, &arg20, &arg21, &arg22, &arg23, &arg24, &arg25, &arg26, &arg27, &arg28, &arg29, &arg30, &arg31, &arg32, &arg33, &arg34, &arg35, &arg36, &arg37, &arg38, &arg39, &arg40, &arg41, &arg42, &arg43, &arg44, &arg45, &arg46, &arg47, &arg48, &arg49, &arg50, &arg51, &arg52, &arg53, &arg54, &arg55, &arg56, &arg57, &arg58, &arg59, &arg60, &arg61, &arg62, &arg63, &arg64, &arg65, &arg66, &arg67, &arg68, &arg69, &arg70, &arg71, &arg72, &arg73, &arg74, &arg75, &arg76, &arg77, &arg78, &arg79, &arg80, &arg81, &arg82, &arg83, &arg84))
    return NULL;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  x2 = (_Bool)_cffi_to_c__Bool(arg2);
  if (x2 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  x3 = (_Bool)_cffi_to_c__Bool(arg3);
  if (x3 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg4, (char **)&x4);
  if (datasize != 0) {
    x4 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg4, (char **)&x4,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg5, (char **)&x5);
  if (datasize != 0) {
    x5 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg5, (char **)&x5,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x6 = _cffi_to_c_int(arg6, int);
  if (x6 == (int)-1 && PyErr_Occurred())
    return NULL;

  x7 = _cffi_to_c_int(arg7, int);
  if (x7 == (int)-1 && PyErr_Occurred())
    return NULL;

  x8 = (double)_cffi_to_c_double(arg8);
  if (x8 == (double)-1 && PyErr_Occurred())
    return NULL;

  x9 = (double)_cffi_to_c_double(arg9);
  if (x9 == (double)-1 && PyErr_Occurred())
    return NULL;

  x10 = (double)_cffi_to_c_double(arg10);
  if (x10 == (double)-1 && PyErr_Occurred())
    return NULL;

  x11 = (double)_cffi_to_c_double(arg11);
  if (x11 == (double)-1 && PyErr_Occurred())
    return NULL;

  x12 = (double)_cffi_to_c_double(arg12);
  if (x12 == (double)-1 && PyErr_Occurred())
    return NULL;

  x13 = (double)_cffi_to_c_double(arg13);
  if (x13 == (double)-1 && PyErr_Occurred())
    return NULL;

  x14 = (double)_cffi_to_c_double(arg14);
  if (x14 == (double)-1 && PyErr_Occurred())
    return NULL;

  x15 = (double)_cffi_to_c_double(arg15);
  if (x15 == (double)-1 && PyErr_Occurred())
    return NULL;

  x16 = (double)_cffi_to_c_double(arg16);
  if (x16 == (double)-1 && PyErr_Occurred())
    return NULL;

  x17 = (double)_cffi_to_c_double(arg17);
  if (x17 == (double)-1 && PyErr_Occurred())
    return NULL;

  x18 = (double)_cffi_to_c_double(arg18);
  if (x18 == (double)-1 && PyErr_Occurred())
    return NULL;

  x19 = (double)_cffi_to_c_double(arg19);
  if (x19 == (double)-1 && PyErr_Occurred())
    return NULL;

  x20 = (double)_cffi_to_c_double(arg20);
  if (x20 == (double)-1 && PyErr_Occurred())
    return NULL;

  x21 = (double)_cffi_to_c_double(arg21);
  if (x21 == (double)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg22, (char **)&x22);
  if (datasize != 0) {
    x22 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg22, (char **)&x22,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg23, (char **)&x23);
  if (datasize != 0) {
    x23 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg23, (char **)&x23,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg24, (char **)&x24);
  if (datasize != 0) {
    x24 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg24, (char **)&x24,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg25, (char **)&x25);
  if (datasize != 0) {
    x25 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg25, (char **)&x25,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg26, (char **)&x26);
  if (datasize != 0) {
    x26 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg26, (char **)&x26,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg27, (char **)&x27);
  if (datasize != 0) {
    x27 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg27, (char **)&x27,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg28, (char **)&x28);
  if (datasize != 0) {
    x28 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg28, (char **)&x28,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg29, (char **)&x29);
  if (datasize != 0) {
    x29 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg29, (char **)&x29,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg30, (char **)&x30);
  if (datasize != 0) {
    x30 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg30, (char **)&x30,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg31, (char **)&x31);
  if (datasize != 0) {
    x31 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg31, (char **)&x31,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg32, (char **)&x32);
  if (datasize != 0) {
    x32 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg32, (char **)&x32,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg33, (char **)&x33);
  if (datasize != 0) {
    x33 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg33, (char **)&x33,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x34 = (_Bool)_cffi_to_c__Bool(arg34);
  if (x34 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  x35 = (_Bool)_cffi_to_c__Bool(arg35);
  if (x35 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg36, (char **)&x36);
  if (datasize != 0) {
    x36 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg36, (char **)&x36,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg37, (char **)&x37);
  if (datasize != 0) {
    x37 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg37, (char **)&x37,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(39), arg38, (char **)&x38);
  if (datasize != 0) {
    x38 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(39), arg38, (char **)&x38,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(39), arg39, (char **)&x39);
  if (datasize != 0) {
    x39 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(39), arg39, (char **)&x39,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(39), arg40, (char **)&x40);
  if (datasize != 0) {
    x40 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(39), arg40, (char **)&x40,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(39), arg41, (char **)&x41);
  if (datasize != 0) {
    x41 = ((size_t)datasize) <= 640 ? (int *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(39), arg41, (char **)&x41,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg42, (char **)&x42);
  if (datasize != 0) {
    x42 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg42, (char **)&x42,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg43, (char **)&x43);
  if (datasize != 0) {
    x43 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg43, (char **)&x43,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x44 = _cffi_to_c_int(arg44, int);
  if (x44 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg45, (char **)&x45);
  if (datasize != 0) {
    x45 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg45, (char **)&x45,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg46, (char **)&x46);
  if (datasize != 0) {
    x46 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg46, (char **)&x46,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg47, (char **)&x47);
  if (datasize != 0) {
    x47 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg47, (char **)&x47,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg48, (char **)&x48);
  if (datasize != 0) {
    x48 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg48, (char **)&x48,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg49, (char **)&x49);
  if (datasize != 0) {
    x49 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg49, (char **)&x49,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg50, (char **)&x50);
  if (datasize != 0) {
    x50 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg50, (char **)&x50,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg51, (char **)&x51);
  if (datasize != 0) {
    x51 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg51, (char **)&x51,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg52, (char **)&x52);
  if (datasize != 0) {
    x52 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg52, (char **)&x52,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg53, (char **)&x53);
  if (datasize != 0) {
    x53 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg53, (char **)&x53,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg54, (char **)&x54);
  if (datasize != 0) {
    x54 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg54, (char **)&x54,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg55, (char **)&x55);
  if (datasize != 0) {
    x55 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg55, (char **)&x55,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg56, (char **)&x56);
  if (datasize != 0) {
    x56 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg56, (char **)&x56,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg57, (char **)&x57);
  if (datasize != 0) {
    x57 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg57, (char **)&x57,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg58, (char **)&x58);
  if (datasize != 0) {
    x58 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg58, (char **)&x58,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg59, (char **)&x59);
  if (datasize != 0) {
    x59 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg59, (char **)&x59,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg60, (char **)&x60);
  if (datasize != 0) {
    x60 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg60, (char **)&x60,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x61 = _cffi_to_c_int(arg61, int);
  if (x61 == (int)-1 && PyErr_Occurred())
    return NULL;

  x62 = _cffi_to_c_int(arg62, int);
  if (x62 == (int)-1 && PyErr_Occurred())
    return NULL;

  x63 = (double)_cffi_to_c_double(arg63);
  if (x63 == (double)-1 && PyErr_Occurred())
    return NULL;

  x64 = (double)_cffi_to_c_double(arg64);
  if (x64 == (double)-1 && PyErr_Occurred())
    return NULL;

  x65 = (double)_cffi_to_c_double(arg65);
  if (x65 == (double)-1 && PyErr_Occurred())
    return NULL;

  x66 = (double)_cffi_to_c_double(arg66);
  if (x66 == (double)-1 && PyErr_Occurred())
    return NULL;

  x67 = (double)_cffi_to_c_double(arg67);
  if (x67 == (double)-1 && PyErr_Occurred())
    return NULL;

  x68 = (double)_cffi_to_c_double(arg68);
  if (x68 == (double)-1 && PyErr_Occurred())
    return NULL;

  x69 = (double)_cffi_to_c_double(arg69);
  if (x69 == (double)-1 && PyErr_Occurred())
    return NULL;

  x70 = (double)_cffi_to_c_double(arg70);
  if (x70 == (double)-1 && PyErr_Occurred())
    return NULL;

  x71 = (_Bool)_cffi_to_c__Bool(arg71);
  if (x71 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  x72 = (_Bool)_cffi_to_c__Bool(arg72);
  if (x72 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  x73 = (_Bool)_cffi_to_c__Bool(arg73);
  if (x73 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  x74 = (_Bool)_cffi_to_c__Bool(arg74);
  if (x74 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  x75 = (double)_cffi_to_c_double(arg75);
  if (x75 == (double)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg76, (char **)&x76);
  if (datasize != 0) {
    x76 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg76, (char **)&x76,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg77, (char **)&x77);
  if (datasize != 0) {
    x77 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg77, (char **)&x77,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg78, (char **)&x78);
  if (datasize != 0) {
    x78 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg78, (char **)&x78,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg79, (char **)&x79);
  if (datasize != 0) {
    x79 = ((size_t)datasize) <= 640 ? (double * *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(5), arg79, (char **)&x79,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x80 = (double)_cffi_to_c_double(arg80);
  if (x80 == (double)-1 && PyErr_Occurred())
    return NULL;

  x81 = (double)_cffi_to_c_double(arg81);
  if (x81 == (double)-1 && PyErr_Occurred())
    return NULL;

  x82 = (double)_cffi_to_c_double(arg82);
  if (x82 == (double)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(25), arg83, (char **)&x83);
  if (datasize != 0) {
    x83 = ((size_t)datasize) <= 640 ? (double *)alloca((size_t)datasize) : NULL;
    if (_cffi_convert_array_argument(_cffi_type(25), arg83, (char **)&x83,
            datasize, &large_args_free) < 0)
      return NULL;
  }

  x84 = (_Bool)_cffi_to_c__Bool(arg84);
  if (x84 == (_Bool)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { samfdeepcnv_loop(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24, x25, x26, x27, x28, x29, x30, x31, x32, x33, x34, x35, x36, x37, x38, x39, x40, x41, x42, x43, x44, x45, x46, x47, x48, x49, x50, x51, x52, x53, x54, x55, x56, x57, x58, x59, x60, x61, x62, x63, x64, x65, x66, x67, x68, x69, x70, x71, x72, x73, x74, x75, x76, x77, x78, x79, x80, x81, x82, x83, x84); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  if (large_args_free != NULL) _cffi_free_array_arguments(large_args_free);
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_samfdeepcnv_loop _cffi_d_samfdeepcnv_loop
#endif

static const struct _cffi_global_s _cffi_globals[] = {
  { "samfdeepcnv_loop", (void *)_cffi_f_samfdeepcnv_loop, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 0), (void *)_cffi_d_samfdeepcnv_loop },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  NULL,  /* no fields */
  NULL,  /* no struct_unions */
  NULL,  /* no enums */
  NULL,  /* no typenames */
  1,  /* num_globals */
  0,  /* num_struct_unions */
  0,  /* num_enums */
  0,  /* num_typenames */
  NULL,  /* no includes */
  88,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_samfdeepcnv(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_samfdeepcnv(void) { return NULL; }
#  else
     initsamfdeepcnv(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_samfdeepcnv(void)
{
  return _cffi_init("samfdeepcnv", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initsamfdeepcnv(void)
{
  _cffi_init("samfdeepcnv", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
